In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization

In [2]:
import pandas as pd
import os
import feature_extract
import numpy as np
folder = 'C:/Users/Dell/Downloads/Speech Recognition/unseen data/'
feature = []

for audio in os.listdir(folder):
    audio_path = folder+audio
    z = feature_extract.feature_extraction(audio_path)
    feature.append(z)        # class 4 = Neural  class 5 = Pleasant Surprise   class 6 = Sad
data = pd.DataFrame(feature)

C:/Users/Dell/Downloads/Speech Recognition/unseen data/16b10Fb.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/16b10Lb.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/angry_male.mp3
C:/Users/Dell/Downloads/Speech Recognition/unseen data/JK_n03.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/Joy.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/my_angry.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/my_disgust.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/my_happy.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/my_upset.wav
C:/Users/Dell/Downloads/Speech Recognition/unseen data/neutral_male.mp3


In [3]:
data.head(3)

0           1          2          3      4     5          6     7  \
0 -292.250000   46.570000 -73.849998  49.509998 -28.51 -0.10 -22.469999 -2.27   
1 -243.130005   87.339996 -30.290001  63.970001 -15.73  6.76 -18.580000 -5.19   
2 -381.019989  102.120003  12.580000  14.270000  14.30  8.25  -0.100000  0.20   

       8     9  ...    34    35    36    37    38    39  Mean Pitch  \
0 -13.42 -8.05  ...  5.18  1.77  2.38 -0.50  2.54  1.48  878.539978   
1  -7.07 -5.35  ...  4.25  1.53  2.88  0.19 -1.26  0.21  438.100006   
2  -0.62 -3.05  ... -0.91  0.52 -2.57 -1.47  0.32  1.96  390.369995   

   Mean Energy   HNR   ZCR  
0        13.74 -7.11  0.14  
1        33.49  1.48  0.09  
2        11.45 -4.59  0.05  

[3 rows x 44 columns]

In [4]:
data.columns

Index([            0,             1,             2,             3,
                   4,             5,             6,             7,
                   8,             9,            10,            11,
                  12,            13,            14,            15,
                  16,            17,            18,            19,
                  20,            21,            22,            23,
                  24,            25,            26,            27,
                  28,            29,            30,            31,
                  32,            33,            34,            35,
                  36,            37,            38,            39,
        'Mean Pitch', 'Mean Energy',         'HNR',         'ZCR'],
      dtype='object')

In [5]:
df = data.to_numpy()
reshaped_df = df.reshape(df.shape[0], 1, df.shape[1]) 

In [6]:
from tensorflow.keras.models import load_model
predictions = []
# Load the trained model
lstm_model = load_model('audio_new_lstm_model.keras')

# Predict on the new data
predictions = lstm_model.predict(reshaped_df)

# For classification, you might want to get the class with the highest probability
# class 0 = Angry   class 1 = Disgust   class 2 = Fear   class 3 = Happy
# class 4 = Neural  class 5 = Pleasant Surprise   class 6 = Sad
predicted_class = np.argmax(predictions, axis=-1)

print("Predicted class:", np.round(predictions,2))
print(predicted_class)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step
Predicted class: [[0.1  0.   0.15 0.39 0.   0.35 0.  ]
 [0.01 0.02 0.   0.96 0.   0.   0.  ]
 [0.   0.97 0.   0.   0.   0.   0.03]
 [0.01 0.02 0.02 0.   0.01 0.   0.94]
 [0.   1.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.  ]]
[3 3 1 6 1 1 1 1 1 1]


In [10]:
emotion = ['Angry','Disgust','Fear','Happy','Neutral','Surprise','Sad']
i=0
for audio in os.listdir(folder):
    print(f'Audio File Name: {audio} ------ Emotion Type: {emotion[predicted_class[i]]}')
    i=i+1
    

Audio File Name: 16b10Fb.wav ------ Emotion Type: Happy
Audio File Name: 16b10Lb.wav ------ Emotion Type: Happy
Audio File Name: angry_male.mp3 ------ Emotion Type: Disgust
Audio File Name: JK_n03.wav ------ Emotion Type: Sad
Audio File Name: Joy.wav ------ Emotion Type: Disgust
Audio File Name: my_angry.wav ------ Emotion Type: Disgust
Audio File Name: my_disgust.wav ------ Emotion Type: Disgust
Audio File Name: my_happy.wav ------ Emotion Type: Disgust
Audio File Name: my_upset.wav ------ Emotion Type: Disgust
Audio File Name: neutral_male.mp3 ------ Emotion Type: Disgust
